### ISSUE TITLE
Update Unblocker Link

### ISSUE THREAD

**Issue by lezetho** [sz-games/sz-games.github.io#1]
I'm suggesting to add another link for a unblocker: https://ubhub-a358941cfbbb.herokuapp.com/photography

This link is unblocked on most networks as the current one does not work.

**Comment by GetLazeredKid** [comment]
whenever i open it my antivirus says that there is malware in it

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by a1game** [comment]
its possible to rebuild using href var starting with "/" rather then "sz-games.github.io/" to allow unblocking using cloudflare pages or others
