### ISSUE TITLE
Cat Ninja, Smash Karts - Error 404

### ISSUE THREAD

**Issue by michoko999** [sz-games/sz-games.github.io#10]
Hello, a 404 error appears when loading the game [Cat Ninja](https://sz-games.github.io/games/game.html?game=https://images-opensocial.googleusercontent.com/gadgets/ifr?url=https://s3.amazonaws.com/production-assetsbucket-8ljvyr1xczmb/1ee20621-61bc-4ec8-a8ec-5e839c2e6edc%2Fcat-ninja.xm)

**Comment by michoko999** [comment]
a 404 error appears when loading the game [Smash Karts] (https://sz-games.github.io/games/game.html?game=https://mr-funkinguy.github.io/75/projects/smashkarts/index.html)

**Comment by Mr-funkinguy** [comment]
ill get to fixing it thanks
