### ISSUE TITLE
DMCA

### ISSUE THREAD

**Issue by nathanielrz** [sz-games/sz-games.github.io#3]
Remove minecraft, and all the fnaf games, subway surfers and you will get into serious trouble and its illegal.
They are paid games, trademarked and also copyrighted. I'm giving you a warning, even though you might be on an alternative account the FBI and GitHub is still capable of finding you.

TRADEMARKKS: https://digital.gov/resources/u-s-trademark-law
COPYRIGHT: https://www.copyright.gov/title17/

THIS IS JUST A WARNING OF WHAT YOU CHOSE TO BE INVOLVED WITH.

**Comment by nathanielrz** [comment]
No your all good.

**Comment by Mr-funkinguy** [comment]
> Remove minecraft, and all the fnaf games, subway surfers and you will get into serious trouble and its illegal.
> 
> They are paid games, trademarked and also copyrighted. I'm giving you a warning, even though you might be on an alternative account the FBI and GitHub is still capable of finding you.
> 
> 
> 
> TRADEMARKKS: https://digital.gov/resources/u-s-trademark-law
> 
> COPYRIGHT: https://www.copyright.gov/title17/
> 
> 
> 
> THIS IS JUST A WARNING OF WHAT YOU CHOSE TO BE INVOLVED WITH.

First the Minecraft build isn't official and is made by a different creator 

The fnaf games are recreations of the originals they aren't official builds of the games and are just copy's that people made

**Comment by nathanielrz** [comment]
Incorrect, they are trademarks do you not understand? Research it, doesn't matter if they are remakes you can still get sued for it. Minecraft is the real one in Java it uses the actual files compiled to html.

**Comment by mandudemandude** [comment]
> Incorrect, they are trademarks do you not understand? Research it, doesn't matter if they are remakes you can still get sued for it. Minecraft is the real one in Java it uses the actual files compiled to html.

Just open up a new issue, pretty sure they have to do somthing about it

**Comment by a1game** [comment]
Assets - Copyright
Name - Trademark
Audio - Copyright
its still stolen assets also you dont credit anyone you get games from

**Comment by GetLazeredKid** [comment]
Wdym?
